export const AstronomyWords = [
  { word: 'Exoplanet Discovery', definition: 'The process of finding planets outside our solar system known as exoplanets' },
  { word: 'Gravitational Lensing', definition: 'A phenomenon where a massive object like a galaxy or black hole bends the light from objects behind it' },
  { word: 'Hertzsprung Russell Diagram', definition: 'A graph in astronomy classifying stars by luminosity, spectral type, temperature, and evolutionary stage' },
  { word: 'Cosmic Microwave Background', definition: 'The afterglow radiation left over from the Big Bang providing a snapshot of the early universe' },
  { word: 'Spectral Classification', definition: 'A system categorizing stars based on their spectra, primarily based on temperature' },
  { word: 'Chandrasekhar Limit', definition: 'The maximum mass a stable white dwarf star can have, beyond which it would collapse' },
  { word: 'Red Supergiant Star', definition: 'A type of star that is very large and luminous, characterized by a cool surface and a red hue' },
  { word: 'Neutron Star Collision', definition: 'A cataclysmic event where two neutron stars orbit and merge, leading to heavy element formation' },
  { word: 'Doppler Shift Analysis', definition: 'A technique to study the motion of celestial objects based on the Doppler effect' },
  { word: 'Black Hole', definition: 'A region in space with gravitational pull so strong that nothing, not even light, can escape' },
  { word: 'Quasar', definition: 'A highly luminous and active galactic nucleus powered by a supermassive black hole' },
  { word: 'Dark Matter', definition: 'A form of matter thought to account for approximately 85 percent of the matter in the universe' },
  { word: 'Pulsar', definition: 'A highly magnetized rotating neutron star that emits beams of electromagnetic radiation' },
  { word: 'Big Bang Theory', definition: 'The prevailing cosmological model explaining the origin of the universe from a singular point' },
  { word: 'Event Horizon', definition: 'The boundary around a black hole beyond which no radiation or matter can return' },
  { word: 'Galactic Halo', definition: 'A spherical region of a galaxy, extending beyond its main visible components' },
  { word: 'White Dwarf', definition: 'A small, dense star that is the remnant of a low-mass star like our Sun' },
  { word: 'Supernova', definition: 'A powerful and luminous stellar explosion marking the end of a massive star' },
  { word: 'Cosmology', definition: 'The science of the origin and development of the universe' },
  { word: 'Interstellar Medium', definition: 'The matter that exists in the space between the star systems in a galaxy' },
  { word: 'Orbit', definition: 'The curved path of a celestial object or spacecraft around a star, planet, or moon' },
  { word: 'Asteroid Belt', definition: 'A region of space between the orbits of Mars and Jupiter filled with asteroids' },
  { word: 'Redshift', definition: 'A phenomenon where the spectrum of light from an object moving away is shifted toward the red' },
  { word: 'Protostar', definition: 'A very young star still in the process of formation from a collapsing cloud of gas and dust' },
  { word: 'Nebula', definition: 'A giant cloud of dust and gas in space, often the birthplace of stars and planets' },
  { word: 'Gamma Ray Burst', definition: 'A highly energetic explosion observed in distant galaxies believed to be associated with collapsing stars' },
  { word: 'Accretion Disk', definition: 'A structure formed by diffused material in orbital motion around a central body' },
  { word: 'Solar Flare', definition: 'A sudden eruption of intense high-energy radiation from the suns surface' },
  { word: 'Magnetosphere', definition: 'The region of space surrounding an astronomical object where charged particles are controlled by that objects magnetic field' },
  { word: 'Star Cluster', definition: 'A group of stars that are physically related through gravitational attraction and relatively close to each other' },
  { word: 'Lunar Eclipse', definition: 'An event where the Earth comes between the Sun and the Moon, casting a shadow on the Moon' },
  { word: 'Solar Eclipse', definition: 'An event where the Moon passes between the Sun and Earth, casting a shadow on Earth' },
  { word: 'Aurora', definition: 'A natural light display in the Earths sky predominantly seen in high-latitude regions' },
  { word: 'Solar Wind', definition: 'The stream of charged particles released from the upper atmosphere of the Sun' },
  { word: 'Cosmic Ray', definition: 'A highly energetic atomic nucleus or other particle traveling through space at nearly the speed of light' },
  { word: 'Extragalactic Astronomy', definition: 'The study of objects outside our galaxy, including other galaxies and phenomena' },
  { word: 'Infrared Astronomy', definition: 'The study of astronomical objects visible in infrared radiation' },
  { word: 'Space Telescope', definition: 'A telescope located in space to observe distant planets, galaxies, and other celestial objects' },
  { word: 'Astrophysics', definition: 'The branch of astronomy concerned with the physical nature of stars and other celestial bodies' },
  { word: 'Celestial Sphere', definition: 'An imaginary sphere of gigantic radius with the Earth at its center on which all celestial bodies are visualized' },
  { word: 'Elliptical Orbit', definition: 'The oval-shaped path of a celestial body as it orbits another body' },
  { word: 'Galaxy', definition: 'A massive, gravitationally bound system of stars, stellar remnants, interstellar gas, dust, and dark matter' },
  { word: 'Milky Way', definition: 'The galaxy that contains our Solar System, characterized by its spiral arm structure' },
  { word: 'Stellar Evolution', definition: 'The process by which a star changes over the course of time' },
  { word: 'Umbra', definition: 'The darkest part of a shadow, where light from a light source is completely blocked by an occluding body' },
  { word: 'Penumbra', definition: 'The region in which only a portion of light from a light source is obscured by an occluding body' },
  { word: 'Solar System', definition: 'The collection of eight planets and their moons orbiting the sun, along with smaller bodies like asteroids and comets' },
  { word: 'Light Year', definition: 'A unit of astronomical distance equivalent to the distance light travels in one year' },
  { word: 'Parsec', definition: 'A unit of length used to measure large distances to astronomical objects outside the solar system' },
  { word: 'Supergiant', definition: 'An extremely large and bright star, larger than a giant star' },
  { word: 'Variable Star', definition: 'A star whose brightness as seen from Earth fluctuates' },
  { word: 'Zodiac', definition: 'A belt of the heavens within about 8 degrees on either side of the ecliptic, including all apparent positions of the sun, moon, and most familiar planets' },
  { word: 'Observatory', definition: 'A location used for observing terrestrial or celestial events' },
  { word: 'Planetary Nebula', definition: 'A type of emission nebula consisting of an expanding, glowing shell of ionized gas ejected from old red giant stars late in their lives' }
];
