export const AstronomyWords = [
  'Exoplanet Discovery',
  'Gravitational Lensing',
  'Hertzsprung Russell Diagram',
  'Cosmic Microwave Background',
  'Spectral Classification',
  'Chandrasekhar Limit',
  'Red Supergiant Star',
  'Neutron Star Collision',
  'Doppler Shift Analysis',
  'Dark Matter Halo',
  'Pulsar Wind Nebula',
  'Black Hole Singularity',
  'Main Sequence Star',
  'Interstellar Medium',
  'Quasar Energy Output',
  'Roche Lobe Overflow',
  'Hydrostatic Equilibrium',
  'Keplers Laws of Planetary Motion',
  'Trans Neptunian Object',
  'Radio Galaxy Emission',
  'Wolf Rayet Star',
  'Solar Prominence Activity',
  'Accretion Disk Dynamics',
  'Cepheid Variable Star',
  'Baryon Acoustic Oscillations',
  'Magnetar Surface Temperature',
  'Galactic Center Region',
  'Cosmological Redshift',
  'Herbig Haro Object',
  'Lyman Alpha Blob',
  'Orbital Resonance Phenomenon',
  'Solar Neutrino Problem',
  'Hubble Space Telescope Discoveries',
  'Interplanetary Dust Cloud',
  'Planetary Nebula Formation',
  'James Webb Space Telescope',
  'Brown Dwarf Identification',
  'Stellar Nucleosynthesis Process',
  'Galaxy Merger Events',
  'Einstein Ring Observation',
  'Gamma Ray Burst Afterglow',
  'Asteroid Belt Composition',
  'Heliospheric Current Sheet',
  'Stellar Black Hole',
  'Orion Nebula Cluster',
  'Solar Magnetic Cycle',
  'Milky Way Satellite Galaxies',
  'Kuiper Belt Objects',
  'Zodiacal Light Phenomenon',
  'Supermassive Black Hole',
];
