export const ComputerScienceWords = [
  'Artificial Intelligence',
  'Machine Learning',
  'Data Structures',
  'Algorithms',
  'Big Data',
  'Cloud Computing',
  'Internet of Things',
  'Blockchain Technology',
  'Cybersecurity',
  'Cryptography',
  'Software Development',
  'Agile Methodology',
  'Object Oriented Programming',
  'Functional Programming',
  'Database Management',
  'Operating Systems',
  'Computer Networks',
  'Parallel Computing',
  'Quantum Computing',
  'Human Computer Interaction',
  'Virtual Reality',
  'Augmented Reality',
  'User Experience Design',
  'Information Theory',
  'Compiler Design',
  'Web Development',
  'Mobile Applications',
  'Application Programming Interface Design',
  'Version Control Systems',
  'Open Source Software',
  'Computer Graphics',
  'Animation Techniques',
  'Game Development',
  'Digital Signal Processing',
  'Microprocessors',
  'Embedded Systems',
  'Robotics',
  'Automation',
  'Wireless Networking',
  'Network Security',
  'Ethical Hacking',
  'Data Mining',
  'Natural Language Processing',
  'Computer Vision',
  'Image Processing',
  'Pattern Recognition',
  'Distributed Systems',
  'Cloud Storage',
  'Development Operations',
  'Continuous Integration',
  'Software Testing',
  'Performance Tuning',
  'Memory Management',
  'Debugging Techniques',
  'System Architecture',
  'Computational Complexity',
  'Heuristic Analysis',
  'Graph Theory',
  'Sorting Algorithms',
  'Encryption Algorithms',
  'Coding Theory',
  'Error Detection',
  'Data Compression',
  'File Systems',
  'Virtual Machines',
  'Containerization',
  'User Interface Design',
  'Responsive Design',
  'Search Engine Optimization',
  'Content Management Systems',
  'Electronic Commerce Platforms',
  'Digital Marketing',
  'Information Technology Project Management',
  'Technology Consulting',
  'Technology Startups',
  'Venture Capital',
  'Information Technology Service Management',
  'Remote Work Tools',
  'Massive Open Online Course Platforms',
  'Technology Policy',
  'Digital Privacy',
  'Intellectual Property',
  'Software Licenses',
  'Network Protocols',
  'Transmission Control Protocol Internet Protocol Model',
  'Local Area Network Wide Area Network Technologies',
  'Fiber Optics Communication',
  'Satellite Communication',
  'Radio Frequency Identification Systems',
  'Server Administration',
  'Data Center Operations',
  'Mainframe Computing',
  'Legacy Systems',
  'Computational Biology',
  'Health Informatics',
  'Bioinformatics Algorithms',
  'Quantum Information Science',
  'Machine Ethics',
  'Algorithmic Trading',
  'High Frequency Trading',
  'Geographic Information Systems',
  'Computational Finance',
  'Digital Forensics',
];
