export const ComputerScienceWords = [
  { word: 'Algorithm', definition: 'A step by step procedure or formula for solving a problem' },
  { word: 'Binary', definition: 'A way of representing information using only two options' },
  { word: 'Compiler', definition: 'A program that translates code in a high-level language to machine instructions' },
  { word: 'Data Structure', definition: 'A particular way of organizing and storing data in a computer' },
  { word: 'Encryption', definition: 'The process of converting information or data into a code to prevent unauthorized access' },
  { word: 'Function', definition: 'A named section of a program that performs a specific task' },
  { word: 'Hypertext Markup Language', definition: 'The standard markup language for documents designed to be displayed in a web browser' },
  { word: 'Inheritance', definition: 'An object-oriented programming concept where a new class is created from an existing class' },
  { word: 'Java', definition: 'A high-level, class-based, object-oriented programming language' },
  { word: 'Kernel', definition: 'The central part of an operating system, managing system resources and communication between hardware and software' },
  { word: 'Loop', definition: 'A sequence of instructions that repeats until a certain condition is reached' },
  { word: 'Malware', definition: 'Software designed to interfere with a computers normal functioning' },
  { word: 'Network', definition: 'A group of interconnected computers and other devices' },
  { word: 'Object', definition: 'In programming, a data structure that contains data and methods to manipulate that data' },
  { word: 'Pointer', definition: 'A variable that stores the memory address of another variable' },
  { word: 'Query', definition: 'A request for information from a database' },
  { word: 'Recursion', definition: 'A programming technique where a function calls itself' },
  { word: 'Stack', definition: 'A linear data structure that serves as a collection of elements, with two main operations: push and pop' },
  { word: 'Thread', definition: 'The smallest sequence of programmed instructions that can be managed independently by a scheduler' },
  { word: 'Uniform Resource Locator', definition: 'A reference or address to a resource on the internet' },
  { word: 'Variable', definition: 'A storage location paired with an associated symbolic name, which contains some known or unknown quantity of information referred to as a value' },
  { word: 'Web Hosting', definition: 'A service that allows individuals and organizations to post a website or web page onto the internet' },
  { word: 'Extensible Markup Language', definition: 'A language that defines rules for encoding documents in a format that is both human-readable and machine-readable' },
  { word: 'Yield', definition: 'A programming term that pauses the execution of a function and returns a value, but retains its state to enable function to resume where it left off' },
  { word: 'Zigbee', definition: 'A high-level communication protocol used to create personal area networks with small, low-power digital radios' },
  { word: 'Abstract Class', definition: 'A type of class in object-oriented programming that cannot be instantiated and is typically used as a base class' },
  { word: 'Cloud Computing', definition: 'The practice of using a network of remote servers hosted on the internet to store, manage, and process data' },
  { word: 'Database', definition: 'An organized collection of structured information or data, typically stored electronically in a computer system' },
  { word: 'Exception', definition: 'An event that occurs during the execution of a program that disrupts the normal flow of instructions' },
  { word: 'Firewall', definition: 'A network security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules' },
  { word: 'Gateway', definition: 'A hardware device that acts as a gate between two networks' },
  { word: 'Heuristic', definition: 'A technique designed for solving a problem more quickly when classic methods are too slow' },
  { word: 'Interface', definition: 'A shared boundary across which two separate components of a computer system exchange information' },
  { word: 'JavaScript Object Notation', definition: 'A lightweight data-interchange format that is easy for humans to read and write, and easy for machines to parse and generate' },
  { word: 'Latency', definition: 'The delay before a transfer of data begins following an instruction for its transfer' },
  { word: 'Middleware', definition: 'Software that provides common services and capabilities to applications outside of what is offered by the operating system' },
  { word: 'Node', definition: 'A basic unit of a data structure, such as a linked list or tree data structure' },
  { word: 'Open Source', definition: 'A type of software in which the source code is released under a license in which the copyright holder grants users the rights to study, change, and distribute the software to anyone' },
  { word: 'Pixel', definition: 'The smallest unit of a digital image or graphic that can be displayed and represented on a digital display device' },
  { word: 'Quantum Computing', definition: 'An area of computing focused on developing computer technology based on the principles of quantum theory' },
  { word: 'Router', definition: 'A networking device that forwards data packets between computer networks' },
  { word: 'Syntax', definition: 'The set of rules that defines the combinations of symbols that are considered to be correctly structured programs in a programming language' },
  { word: 'Tuple', definition: 'In programming, an ordered list of elements' },
  { word: 'User Interface', definition: 'The means by which the user and a computer system interact, in particular the use of input devices and software' },
  { word: 'Virtual Reality', definition: 'A simulated experience that can be similar to or completely different from the real world' },
  { word: 'Widget', definition: 'An element of a graphical user interface (GUI) that displays information or provides a specific way for a user to interact with the operating system or an application' },
  { word: 'Cross-Site Scripting', definition: 'A type of security vulnerability typically found in web applications' },
  { word: 'Yottabyte', definition: 'A unit of information or computer storage equal to one septillion bytes' },
  { word: 'Zero-Day Attack', definition: 'A cyber attack that occurs on the same day a weakness is discovered in software, before the software developers have an opportunity to create a patch to fix the vulnerability' }
];
