export const MeteorologyWords = [
  'Atmospheric Pressure',
  'Climate Change Impact',
  'Convective Storm Cells',
  'Dew Point Measurement',
  'El Nino Southern Oscillation',
  'Flash Flood Warning',
  'Global Warming Effects',
  'High Pressure System',
  'Isothermal Layer',
  'Jet Stream Dynamics',
  'Kinetic Energy Transfer',
  'Low Pressure Area',
  'Marine Layer Fog',
  'Nimbus Cloud Formation',
  'Ozone Layer Depletion',
  'Polar Vortex Shift',
  'Quantitative Precipitation Forecast',
  'Radiational Cooling',
  'Stratospheric Ozone',
  'Tornado Warning System',
  'Urban Heat Island',
  'Vapor Pressure Deficit',
  'Warm Front Passage',
  'Xeric Shrubland Climate',
  'Younger Dryas Event',
  'Zonal Wind Pattern',
  'Weather Radar Technology',
  'Thunderstorm Development',
  'Seasonal Monsoon Variation',
  'Relative Humidity Range',
  'Precipitation Distribution',
  'Ocean Currents Interaction',
  'Mesocyclone Structure',
  'Lightning Strike Analysis',
  'Hydrological Cycle',
  'Greenhouse Gas Emissions',
  'Frontal Boundary Layer',
  'Evapotranspiration Rate',
  'Cyclonic Storm Formation',
  'Barometric Pressure Trend',
  'Anticyclonic Rotation',
  'Weather Forecasting Models',
  'Typhoon Intensity Scale',
  'Snowfall Accumulation',
  'Rain Shadow Effect',
  'Microburst Wind Gusts',
  'Land Breeze Cycle',
  'Hurricane Evacuation Plan',
  'Geostrophic Wind Balance',
  'Frost Point Calculation',
  'Eddy Covariance Method',
  'Drought Severity Index',
  'Cloud Seeding Techniques',
  'Atmospheric Convection Currents'
  ];
