export const MeteorologyWords = [
  { word: 'Atmosphere', definition: 'The layer of gases surrounding the planet Earth that is retained by Earths gravity' },
  { word: 'Barometer', definition: 'An instrument measuring atmospheric pressure, used especially in forecasting the weather' },
  { word: 'Cyclone', definition: 'A large scale air mass that rotates around a strong center of low atmospheric pressure' },
  { word: 'Dew Point', definition: 'The atmospheric temperature below which water droplets begin to condense and dew can form' },
  { word: 'El Nino', definition: 'A climate pattern that describes the unusual warming of surface waters in the eastern tropical Pacific Ocean' },
  { word: 'Fog', definition: 'A thick cloud of tiny water droplets suspended in the atmosphere at or near the Earths surface' },
  { word: 'Gale', definition: 'A very strong wind, typically used in the context of meteorology' },
  { word: 'Humidity', definition: 'The amount of water vapor present in the air' },
  { word: 'Isobar', definition: 'A line on a map connecting points having the same atmospheric pressure at a given time or on average over a given period' },
  { word: 'Jet Stream', definition: 'A narrow, variable band of very strong, predominantly westerly air currents encircling the globe several miles above the earth' },
  { word: 'Katabatic Wind', definition: 'A wind that carries high-density air from a higher elevation down a slope under the force of gravity' },
  { word: 'Lithosphere', definition: 'The rigid outer part of the earth, consisting of the crust and upper mantle' },
  { word: 'Monsoon', definition: 'A seasonal prevailing wind in the region of South and Southeast Asia, blowing from the southwest between May and September and bringing rain' },
  { word: 'Nimbus', definition: 'A cloud forming a towering mass with a flat base at fairly low altitude and often a flat top, as in thunderstorms' },
  { word: 'Occluded Front', definition: 'A composite front produced by occlusion of a cold front by a warm front' },
  { word: 'Precipitation', definition: 'Any form of water - liquid or solid - that falls from clouds and reaches the ground' },
  { word: 'Quasi Biennial Oscillation', definition: 'A quasi-periodic oscillation of the equatorial zonal wind between easterlies and westerlies in the tropical stratosphere' },
  { word: 'Radiosonde', definition: 'An instrument carried by balloon or other means to various levels of the atmosphere and transmitting measurements by radio' },
  { word: 'Squall', definition: 'A sudden, sharp increase in wind speed lasting minutes, contrary to a wind gust lasting seconds' },
  { word: 'Tornado', definition: 'A rapidly rotating column of air that is in contact with both the surface of the Earth and a cumulonimbus cloud or, in rare cases, the base of a cumulus cloud' },
  { word: 'Updraft', definition: 'An upward current or draft of air' },
  { word: 'Vortex', definition: 'A region in a fluid in which the flow revolves around an axis line, which may be straight or curved' },
  { word: 'Weather', definition: 'The state of the atmosphere at a place and time as regards heat, dryness, sunshine, wind, rain, etc' },
  { word: 'Xerophyte', definition: 'A species of plant that has adapted to survive in an environment with little liquid water, such as a desert' },
  { word: 'Yield', definition: 'In meteorology, it often refers to the amount of water or other precipitation produced from clouds' },
  { word: 'Zephyr', definition: 'A soft gentle breeze' },
  { word: 'Albedo', definition: 'The proportion of the incident light or radiation that is reflected by a surface, typically that of a planet or moon' },
  { word: 'Blizzard', definition: 'A severe snowstorm with high winds and low visibility' },
  { word: 'Climate', definition: 'The weather conditions prevailing in an area in general or over a long period' },
  { word: 'Drought', definition: 'A prolonged period of abnormally low rainfall, leading to a shortage of water' },
  { word: 'Evaporation', definition: 'The process of turning from liquid into vapor' },
  { word: 'Front', definition: 'A boundary separating two masses of air of different densities, and is the principal cause of meteorological phenomena' },
  { word: 'Gust', definition: 'A brief, strong rush of wind' },
  { word: 'Hail', definition: 'Pellets of frozen rain that fall in showers from cumulonimbus clouds' },
  { word: 'Isotherm', definition: 'A line on a map connecting points having the same temperature at a given time or on average over a given period' },
  { word: 'Knollenberg Counter', definition: 'A device used to measure the size and number of cloud particles' },
  { word: 'La Nina', definition: 'A climate pattern that describes the cooling of surface ocean waters along the tropical west coast of South America' },
  { word: 'Meteorology', definition: 'The science that deals with the phenomena of the atmosphere, especially weather and weather conditions' },
  { word: 'Nephology', definition: 'The study of clouds and cloud formation' },
  { word: 'Ozone Layer', definition: 'A layer in the earths stratosphere containing a high concentration of ozone, which absorbs most of the ultraviolet radiation reaching the earth from the sun' },
  { word: 'Pyranometer', definition: 'An instrument for measuring solar radiation' },
  { word: 'Relative Humidity', definition: 'The ratio of the partial pressure of water vapor to the equilibrium vapor pressure of water at a given temperature' },
  { word: 'Storm Surge', definition: 'A rising of the sea as a result of atmospheric pressure changes and wind associated with a storm' },
  { word: 'Thermocline', definition: 'A steep temperature gradient in a body of water such as a lake or ocean, marked by a layer above and below which the water is at different temperatures' },
  { word: 'Ultraviolet Index', definition: 'An international standard measurement of the strength of ultraviolet radiation from the sun at a particular place on a particular day' },
  { word: 'Visibility', definition: 'The distance one can clearly see' },
  { word: 'Water Cycle', definition: 'The cycle of processes by which water circulates between the earths oceans, atmosphere, and land' },
  { word: 'Xenon Flash Lamp', definition: 'A lamp that produces a very brief but very bright flash of light for high-speed photography' },
  { word: 'Younger Dryas', definition: 'A period of rapid cooling in the Northern Hemisphere near the end of the Pleistocene epoch' },
  { word: 'Zenith', definition: 'The point in the sky or celestial sphere directly above an observer' },
  { word: 'Anemometer', definition: 'An instrument for measuring the speed of the wind' },
  { word: 'Buoyancy', definition: 'The ability or tendency of something to float in water or air or some other fluid' },
  { word: 'Condensation', definition: 'The conversion of a vapor or gas to a liquid' },
  { word: 'Derecho', definition: 'A widespread, long-lived wind storm that is associated with a band of rapidly moving showers or thunderstorms' },
  { word: 'Eddy', definition: 'A circular movement of water, counter to a main current, causing a small whirlpool' },
  { word: 'Flash Flood', definition: 'A rapid flooding of geomorphic low-lying areas - washes, rivers, dry lakes and basins' },
  { word: 'Greenhouse Effect', definition: 'The trapping of the suns warmth in a planets lower atmosphere' },
  { word: 'Hygrometer', definition: 'An instrument for measuring the humidity of the air or a gas' },
  { word: 'Inversion', definition: 'A reversal of the normal behavior of temperature in the troposphere, in which a layer of cool air at the surface is overlain by a layer of warmer air' },
  { word: 'Koppen Climate Classification', definition: 'A widely used vegetation-based empirical climate classification system' },
  { word: 'Lenticular Cloud', definition: 'A lens-shaped cloud that normally develops on the downwind side of a mountain or mountain range' }
];
