export const OceanologyWords = [
  'Abyssal Plain Formation',
'Brackish Water Ecosystem',
'Continental Shelf Edge',
'Deep Sea Trench',
'El Nino Oceanic Effect',
'Fjord Formation Process',
'Global Thermohaline Circulation',
'Hydrothermal Vent Systems',
'Intertidal Zone Life',
'Jet Stream Influence',
'Kelp Forest Ecology',
'Longshore Drift Current',
'Mangrove Swamp Habitat',
'Nektonic Organism Behavior',
'Ocean Acidification Impact',
'Pelagic Zone Features',
'Quaternary Marine Terraces',
'Rip Current Dynamics',
'Salt Marsh Environment',
'Tidal Range Variation',
'Upwelling Zones',
'Volcanic Island Formation',
'Wave Refraction Patterns',
'Xenophyophore Distribution',
'Yellow Sea Characteristics',
'Zooplankton Migration',
'Sea Surface Temperature',
'Marine Biodiversity Loss',
'Ocean Current Disruption',
'Phytoplankton Blooms',
'Coral Reef Bleaching',
'Arctic Ocean Permafrost',
'Beach Erosion Control',
'Coastal Zone Management',
'Deep Ocean Exploration',
'Estuarine Circulation',
'Fishery Resource Assessment',
'Great Barrier Reef Threats',
'Harmful Algal Blooms',
'Iceberg Calving Process',
'Jellyfish Population Surge',
'Krill Harvesting Impact',
'Littoral Drift Barrier',
'Maritime Climate Influence',
'Nautical Charting Advances',
'Oceanographic Satellite Data',
'Planktonic Community Structure',
'Reef Ecosystem Resilience',
'Submarine Canyon Formation',
'Thermal Vent Ecosystems',
'Underwater Glacial Melting',
'Vortex Shedding in Currents',
'Whale Migration Pathways',
'Eelgrass Meadow Preservation',
'Gyre Circulation Anomalies',
'Island Biogeography Theory',
'Ocean Floor Mapping',
'Seamount Geology Study',
  ];
  