export const OceanologyWords = [
  { word: 'Abyssal Plain', definition: 'A flat or very gently sloping area of the deep ocean basin floor' },
  { word: 'Brackish', definition: 'Water that has more salinity than freshwater but not as much as seawater' },
  { word: 'Coral Bleaching', definition: 'The loss of color in corals due to stress-induced expulsion of symbiotic unicellular algae' },
  { word: 'Downwelling', definition: 'The process of accumulation and sinking of higher density material beneath lower density material' },
  { word: 'El Nino', definition: 'A complex weather pattern resulting from variations in ocean temperatures in the Equatorial Pacific' },
  { word: 'Fathom', definition: 'A unit of length equal to six feet, chiefly used in reference to the depth of water' },
  { word: 'Gyre', definition: 'A large system of circular ocean currents formed by global wind patterns and forces created by Earths rotation' },
  { word: 'Hydrothermal Vent', definition: 'An opening in the sea floor out of which heated mineral-rich water flows' },
  { word: 'Intertidal Zone', definition: 'The area of the foreshore and seabed that is exposed to the air at low tide and submerged at high tide' },
  { word: 'Jet Stream', definition: 'A narrow, variable band of very strong, predominantly westerly air currents encircling the globe several miles above the earth' },
  { word: 'Krill', definition: 'Small crustaceans found throughout the ocean, used as a food source for many marine animals' },
  { word: 'Littoral Zone', definition: 'The part of a sea, lake or river that is close to the shore' },
  { word: 'Mangrove', definition: 'A tree or shrub that grows in chiefly tropical coastal swamps that are flooded at high tide' },
  { word: 'Nautical Mile', definition: 'A unit of measurement used in both air and marine navigation, equivalent to one minute of latitude' },
  { word: 'Oceanography', definition: 'The study of the physical and biological aspects of the ocean' },
  { word: 'Pelagic', definition: 'Relating to the open sea, especially as opposed to the sea near the coast or the sea floor' },
  { word: 'Quota', definition: 'A fixed share of something that a person or group is entitled to receive or is bound to contribute' },
  { word: 'Reef', definition: 'A ridge of jagged rock, coral, or sand just above or below the surface of the sea' },
  { word: 'Salinity', definition: 'The concentration of salt in water, typically measured in parts per thousand' },
  { word: 'Tsunami', definition: 'A long high sea wave caused by an earthquake, submarine landslide, or other disturbance' },
  { word: 'Upwelling', definition: 'A rising of seawater, magma, or other liquid' },
  { word: 'Vortex', definition: 'A whirling mass of fluid or air, especially a whirlpool or whirlwind' },
  { word: 'Watershed', definition: 'An area or ridge of land that separates waters flowing to different rivers, basins, or seas' },
  { word: 'Xerophytic', definition: 'A species of plant that has adapted to survive in an environment with little liquid water' },
  { word: 'Yield', definition: 'In oceanology, it refers to the amount of fish or seafood that can be sustainably caught' },
  { word: 'Zooplankton', definition: 'Small and microscopic animals that float in the water, especially in the ocean' },
  { word: 'Algae', definition: 'Simple nonflowering plants of a large group that includes the seaweeds and many single-celled forms' },
  { word: 'Bathymetry', definition: 'The measurement of depth of water in oceans, seas, or lakes' },
  { word: 'Continental Shelf', definition: 'The area of seabed around a large landmass where the sea is relatively shallow compared with the open ocean' },
  { word: 'Desalination', definition: 'The process of removing salt from seawater' },
  { word: 'Ecosystem', definition: 'A biological community of interacting organisms and their physical environment' },
  { word: 'Foreshore', definition: 'The part of a shore between the high-water mark and the low-water mark' },
  { word: 'Gulf Stream', definition: 'A warm and swift Atlantic ocean current that originates in the Gulf of Mexico' },
  { word: 'Habitat', definition: 'The natural home or environment of an animal, plant, or other organism' },
  { word: 'Isostasy', definition: 'The equilibrium that exists between parts of the earths crust, which behaves as if it consists of blocks floating on the underlying mantle' },
  { word: 'Jellyfish', definition: 'A free-swimming marine coelenterate with a jellylike bell- or saucer-shaped body that is typically transparent' },
  { word: 'Kelp', definition: 'Large brown seaweeds that make up the order Laminariales' },
  { word: 'Marine', definition: 'Relating to the sea, especially in relation to marine shipping or naval matters' },
  { word: 'Nekton', definition: 'Aquatic animals that are able to swim and move independently of water currents' },
  { word: 'Oceanic Trench', definition: 'A long, narrow, deep depression in the ocean floor, typically one running parallel to a plate boundary' },
  { word: 'Phytoplankton', definition: 'Microscopic marine algae that are the basis of the marine food chain' },
  { word: 'Rip Current', definition: 'A strong, narrow surface current flowing outward from a shore, returning seaward from incoming waves' },
  { word: 'Submarine Canyon', definition: 'A steep-sided valley cut into the seabed of the continental slope' },
  { word: 'Thermocline', definition: 'A steep temperature gradient in a body of water marked by a layer above and below which the water is at different temperatures' },
  { word: 'Undercurrent', definition: 'An underlying current in the sea or a river' },
  { word: 'Vent', definition: 'An opening in the earths crust, often on the ocean floor, from which hot magma, gases, and steam are emitted' },
  { word: 'Wave', definition: 'A long body of water curling into an arched form and breaking on the shore' },
  { word: 'Xenophyophore', definition: 'A type of giant single-celled organism found on the deep ocean floor' },
  { word: 'Yellow Sea', definition: 'A marginal sea of the western Pacific Ocean located between mainland China and the Korean Peninsula' },
  { word: 'Zonal Flow', definition: 'A pattern of meteorological conditions characterized by west-to-east movement of weather systems' }
];
